[general]
app_name = "libra"
log_level = 1
log_path = "./log/"

[server]
grpc_trace_enable = true


[system.trace]
service_name = "client-svr"
host_port = "127.0.0.1:6831"

[grpc.client.hello]
host_port = "127.0.0.1:8001"